-- ═══════════════════════════════════════════════════
-- TRADIE AI — SUPABASE DATABASE SCHEMA
-- Run this entire file in your Supabase SQL Editor
-- supabase.com → your project → SQL Editor → New query
-- ═══════════════════════════════════════════════════

-- ── PROFILES TABLE ──
-- Stores every user's business details, plan, and usage count
CREATE TABLE IF NOT EXISTS profiles (
  id            UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email         TEXT NOT NULL,
  name          TEXT DEFAULT '',
  bizname       TEXT DEFAULT '',
  trade         TEXT DEFAULT '',
  state         TEXT DEFAULT '',
  licence       TEXT DEFAULT '',
  abn           TEXT DEFAULT '',
  plan          TEXT DEFAULT 'free' CHECK (plan IN ('free', 'starter', 'pro', 'power')),
  usage_count   INTEGER DEFAULT 0,
  usage_reset   TIMESTAMPTZ DEFAULT date_trunc('month', now()) + interval '1 month',
  stripe_customer_id TEXT DEFAULT NULL,
  stripe_subscription_id TEXT DEFAULT NULL,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now()
);

-- ── HISTORY TABLE ──
-- Stores every AI output generated by each user
CREATE TABLE IF NOT EXISTS history (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  template      TEXT NOT NULL CHECK (template IN ('quote', 'email', 'jobad', 'complaint', 'followup', 'chat')),
  input         TEXT NOT NULL,
  output        TEXT NOT NULL,
  tokens_used   INTEGER DEFAULT 0,
  created_at    TIMESTAMPTZ DEFAULT now()
);

-- ── INDEXES ──
CREATE INDEX IF NOT EXISTS idx_history_user_id ON history(user_id);
CREATE INDEX IF NOT EXISTS idx_history_created_at ON history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_profiles_email ON profiles(email);

-- ── ROW LEVEL SECURITY ──
-- Makes sure users can only see their own data

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE history ENABLE ROW LEVEL SECURITY;

-- Profiles: users can only read and update their own profile
CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  USING (auth.uid() = id);

-- History: users can only see their own history
CREATE POLICY "Users can view own history"
  ON history FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own history"
  ON history FOR DELETE
  USING (auth.uid() = user_id);

-- Service role can do everything (used by the backend server)
CREATE POLICY "Service role full access to profiles"
  ON profiles FOR ALL
  USING (auth.role() = 'service_role');

CREATE POLICY "Service role full access to history"
  ON history FOR ALL
  USING (auth.role() = 'service_role');

-- ── AUTO UPDATE updated_at ──
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ── VERIFY SETUP ──
-- Run this after the above to confirm tables were created
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
